config/routes.rb
Rails.application.routes.draw do
    root 'home#index'

    resources :musicians do
      resources :bands do
        post '/join_band', to: 'band_musicians#create'
        delete '/leave_band', to: 'band_musicians#destroy'
      end
    end

    resources :songs do
      resources :iterations
    end

    resources :bands, only: [:index]

    namespace :admin do
      resources :dashboard, only: [:index]
    end

    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
end

app/models/musician.rb
class Musician < ApplicationRecord
  has_secure_password

  validates :username, uniqueness: true, presence: true
  validates_presence_of :password, require: true, allow_nil: true
  validates_presence_of :name,
                        :profile,
                        :instrument

  enum role: ["default", "admin"]

  has_many :band_musicians, dependent: :destroy
  has_many :bands, through: :band_musicians

  def find_songs
    bands.inject([]) do |collector, band|
      band.songs.each do |song|
        collector << song
        collector
      end
    end
  end

end

app/controllers/musicians_controller.rb
class MusiciansController < ApplicationController
  before_action :set_musician, only: [:show, :edit, :destroy, :update]

  def index
    @musicians = Musician.all
  end

  def new
    @musician = Musician.new
  end

  def create
    @musician = Musician.new(musician_params)
    if @musician.save
      session[:musician_id] = @musician.id
      redirect_to musician_path(@musician)
    else
      flash.now[:alert] = @musician.errors.full_messages.join("<br>").html_safe
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @musician.update(musician_params)
    if @musician.save
      flash[:success] = "Profile updated!"
      redirect_to musician_path(@musician)
    else
      flash.now[:alert] = @musician.errors.full_messages.join("<br>").html_safe
      render :edit
    end
  end

  def destroy
    if @musician.id == current_user.id
      @musician.destroy
      flash[:success] = "So long space cowboy"

      redirect_to root_path
    end
  end

  private

  def musician_params
    params.require(:musician).permit(:username, :name, :password, :profile, :instrument)
  end

  def set_musician
    @musician = Musician.find(params[:id])
  end
end

app/views/musicians/_form.html.erb
<div class="all-forms">
  <%= form_for @musician, :html => { :class => 'base-forms' } do |f| %>
      <%= f.label :name, class: "cool-label" %>
    <div class="form-group">
      <%= f.text_field :name, class: "form-width" %>
    </div>
      <%= f.label :username, class: "cool-label" %>
    <div class="form-group">
      <%= f.text_field :username, class: "form-width" %>
    </div>
      <%= f.label :instrument, class: "cool-label" %>
    <div class="form-group">
      <%= f.text_field :instrument, class: "form-width" %>
    </div>
      <%= f.label :profile, class: "cool-label" %>
    <div class="form-group">
      <%= f.text_field :profile, class: "form-width" %>
    </div>
      <%= f.label :password, class: "cool-label" %>
    <div class="form-group">
      <%= f.password_field :password, class: "form-width" %>
    </div>
    <div class="form-group">
      <%= f.submit "Start making music", class:"submit-button btn large-button" %>
    </div>
  </div>
</div>
<% end %>

app/views/musicians/edit.html.erb
<div class="row">
  <div class="col-3">
  </div>
  <div class="col-4">
  <%= form_for @musician, :html => { :class => 'base-forms' } do |f| %>
      <%= f.label :name %>
    <div class="form-group">
      <%= f.text_field :name, class:"input-medium" %>
    </div>
      <%= f.label :instrument %>
    <div>
      <%= f.text_field :instrument %>
    </div>
      <%= f.label :profile %>
    <div class="form-group">
      <%= f.text_field :profile %>
    </div>
    <div class="form-group">
      <%= f.submit "Update profile", class:"submit-button btn" %>
    </div>
  </div>
</div>
<% end %>

app/views/musicians/index.html.erb
<h1> Musicians </h1>
<% @musicians.each do |musician| %>
<%= link_to musician_path(musician) do %>
<div class="mp-container">
  <div class="picture-container">
    <div class="imgdiv">
    </div>
  </div>
  <div class="profile-container">
    <p class="profile-text"><strong>Name:</strong> <%= musician.name %></p>
    <p class="profile-text"><strong>Instrument:</strong> <%= musician.instrument %></p>
    <p class="profile-text"><strong>Profile:</strong> <%= musician.profile %></p>
  </div>
</div>
<% end %>

<% end %>

app/views/musicians/new.html.erb
<%= render partial:"form" %>

app/views/musicians/show.html.erb
<h1 class="show-headings">Musician profile</h1>
<% if current_user && (@musician.id == current_user.id) %>
  <div class="musician-profile-manager">
    <h1 class="musician-profile-heading"> Your Profile </h1>
    <%= link_to edit_musician_path(current_user) do %>
      <i class="far fa-edit"><span class="hidden">edit</span></i></i>
    <% end %>
    <%= link_to musician_path(current_user), method:"delete", data: {confirm: "Are you sure?"} do %>
      <i class="fas fa-trash-alt"><span class="hidden">delete</span></i></i>
    <% end %>
  </div>
<% end %>

<div class="mp-show-container">
  <div class="musician-container-show">
    <div class="imgdiv">
    </div>
    <h4 class="profile-heading">Name:</h4>
    <p class="profile-text"><%= @musician.name %></p>
    <h4 class="profile-heading">Instrument:</h4>
    <p class="profile-text"><%= @musician.instrument %></p>
    <h4 class="profile-heading">Profile:</h4>
    <p class="profile-text"><%= @musician.profile %></p>
  </div>
  <div class="musician-container-band-show">
  <h4 class="band-profile-heading">Bands</h4>
  <% if @musician.bands.length > 0 %>
    <% @musician.bands.each do |band| %>
      <%= link_to band.name, musician_band_path(@musician, band), class:"btn submit-button large-button" %>
      <% end %>
    <% else %>
      <i class="fas fa-microphone-alt-slash"></i>
      <%= link_to "Need a band?", musician_bands_path(current_user), class:"btn submit-button large-button" %>
    <% end %>
  </div>
</div>
  <% if current_user && (@musician.id == current_user.id) %>
    <div id="create-button">
      <%= link_to "Create a band", new_musician_band_path(@musician), class: "btn submit-button large-button" %>
    </div>
    <div id="my-song-button">
      <%= link_to "My songs", "/songs?musician=#{@musician.id}", class: "btn submit-button large-button" %>
    </div>
<% end %>