config/routes.rb
Rails.application.routes.draw do
    root 'home#index'

    resources :musicians do
      resources :bands do
        post '/join_band', to: 'band_musicians#create'
        delete '/leave_band', to: 'band_musicians#destroy'
      end
    end

    resources :songs do
      resources :iterations
    end

    resources :bands, only: [:index]

    namespace :admin do
      resources :dashboard, only: [:index]
    end

    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
end

app/views/partials/_anonymousnav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Ensemble", root_path, class:"navbar-brand", id:"nav-logo" %>
  <button id="nav-toggle-button" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "signup", new_musician_path, class:"nav-link text-white text-right link-pink-border" %>
      </li>
      <li class="nav-item">
        <%= link_to "login", login_path, class:"nav-link text-white text-right link-blue-border" %>
      </li>
    </ul>
  </div>
</nav>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Ensemble", root_path, class:"navbar-brand", id:"nav-logo" %>
  <button id="nav-toggle-button" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Profile", musician_path(current_user), class:"nav-link text-white text-right link-pink-border" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Join a band", bands_path, class:"nav-link text-white text-right link-pink-border" %>
      </li>
      <li class="nav-item">
        <%= link_to "Write a song", new_song_path, class:"nav-link text-white text-right link-pink-border" %>
      </li>
      <li class="nav-item">
        <%= link_to "Create a band", new_musician_band_path(current_user), class:"nav-link text-white text-right link-pink-border" %>
      </li>
      <li class="nav-item">
        <%= link_to "Settings", edit_musician_path(current_user), class:"nav-link text-white text-right link-pink-border" %>
      </li>
      <% if current_user.admin? %>
      <li class="nav-item">
        <%= link_to "Dashboard", admin_dashboard_index_path, class:"nav-link text-white text-right link-pink-border" %>
      </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "Logout", logout_path, method:"delete", class:"nav-link text-white text-right link-blue-border" %>
      </li>
    </ul>
  </div>
</nav>