config/routes.rb
Rails.application.routes.draw do
    root 'home#index'

    resources :musicians do
      resources :bands do
        post '/join_band', to: 'band_musicians#create'
        delete '/leave_band', to: 'band_musicians#destroy'
      end
    end

    resources :songs do
      resources :iterations
    end

    resources :bands, only: [:index]

    namespace :admin do
      resources :dashboard, only: [:index]
    end

    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
end

app/models/song.rb
class Song < ApplicationRecord
  validates_presence_of :title,
                        :timing,
                        :genre

  belongs_to :band
  has_many :iterations, dependent: :destroy

  def self.by_genre
    group(:genre).count
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :destroy, :edit, :update]

  def new
    @song = Song.new
  end

  def create
    @band = Band.find(song_params[:band_id])
    @song = @band.songs.create(song_params)

    redirect_to song_path(@song)
  end

  def index
    if params[:musician]
      @songs = Musician.find(params[:musician]).find_songs
    else
      @songs = Song.all
    end
  end

  def show
    @band = Band.find(@song.band_id)
    @iteration = Iteration.new
    @iteration_last = @song.iterations.last
  end

  def destroy
    @band = Band.find(@song.band_id)
    @song.destroy

    redirect_to musician_band_path(current_user, @band)
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to song_path(@song)
    else
      render :edit
    end
  end

  private

  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:timing, :genre, :title, :band_id, :musician_id)
  end
end

app/views/songs/edit.html.erb
<div class="col-sm-12 .col-centered text-center">
  <div class="profile-container">
  <%= form_for @song, :html => { :class => 'align-forms' } do |f| %>
      <%= f.label :title %>
    <div class="form-group">
      <%= f.text_field :title, class:"input-medium" %>
    </div>
      <%= f.label :timing %>
    <div class="form-group">
      <%= f.text_field :timing %>
    </div>
      <%= f.label :genre %>
    <div>
    <div class="form-group">
      <%= f.text_field :genre %>
    </div>
    <div class="form-group">
      <%= f.submit "Update song", class:"submit-button btn" %>
    </div>
  </div>
</div>
<% end %>

app/views/songs/index.html.erb
<h1> Songs </h1>
<% @songs.each do |song| %>
<%= link_to song_path(song) do %>
<div class="mp-container">
  <div class="picture-container">
    <% if song&.iterations&.last&.recording %>
      <i class="fas fa-play play-override"></i>
    <% else %>
      <i class="fas fa-microphone-alt-slash mic-override"></i>
    <% end %>
  </div>
  <div class="profile-container">
    <p class="profile-text"><strong>Name:</strong> <%= song.title %></p>
    <p class="profile-text"><strong>Genre:</strong> <%= song.genre %></p>
    <p class="profile-text"><strong>Timing:</strong> <%= song.timing %></p>
  </div>
  <div>
    <h4 class="profile-heading"><%= song.band.name %></h4>
  </div>
</div>
<% end %>

<% end %>

app/views/songs/new.html.erb
<div class="all-forms">
  <%= form_for @song, :html => { :class => 'base-forms' } do |f| %>
  <% if current_user && current_user.bands.exists? %>
      <%= f.label :title, class: "cool-label" %>
    <div class="form-group">
      <%= f.text_field :title, class: "form-width" %>
    </div>
      <%= f.label :timing, class: "cool-label" %>
    <div class="form-group">
      <%= f.text_field :timing, class: "form-width" %>
    </div>
      <%= f.label :genre, class: "cool-label" %>
    <div>
    <div class="form-group">
      <%= f.text_field :genre, class: "form-width" %>
    </div>
    <%= f.label :band, class: "cool-label" %>
    <div class="form-group">
      <%= f.collection_select :band_id, current_user.bands.order(:name), :id, :name, {}, {class: "custom-select"} %>
    </div>
    <div class="form-group">
      <%= f.submit "Make the song", class:"submit-button btn large-button" %>
    </div>
    <% else %>
      <p> You need a band to write a song!</p>
      <%= link_to "Create a band", new_musician_band_path(current_user), class:"btn large-button submit-button" %>
    <% end %>
</div>
<% end %>

app/views/songs/show.html.erb
<div class="musician-profile-manager">
<h1 class="musician-profile-heading"> <div class="song-heading">SONG</div> <%= @song.title %></h1>
<% if current_user && @band.user_in_band?(current_user.id) %>
  <%= link_to edit_song_path(@song) do %>
    <i class="far fa-edit"><span class="hidden">edit</span></i></i>
  <% end %>
  <%= link_to song_path(@song), method:"delete", data: {confirm: "Are you sure?"} do %>
    <i class="fas fa-trash-alt"><span class="hidden">delete</span></i></i>
  <% end %>
<% end %>
</div>


<div class="mp-show-container">
  <div class="musician-container-show">
  <h4 class="profile-heading">Genre:</h4>
  <p class="profile-text"><%= @song.genre %></p>
  <h4 class="profile-heading">Timing:</h4>
  <p class="profile-text"><%= @song.timing %></p>
  <h4 class="profile-heading">Made by:</h4>
    <%= link_to @band.name, musician_band_path(current_user, @band), class:"btn submit-button large-button" %>
  </div>
  <div class="musician-container-band-show">
  <h4 class="band-profile-heading">Members</h4>
    <% @band.musicians.each do |musician| %>
      <p class="profile-text"><%= link_to musician.name, musician_path(musician) %> | <%= musician.instrument %></p>
    <% end %>
  </div>
</div>

<% if @iteration_last %>
  <div class="iteration-container-song">
      <h4 class="iteration-heading">Last iteration</h4>
      <h4 class="profile-heading"> Author: </h4>
      <p class="profile-text"> <%= @iteration_last.author %></p>
      <h4 class="profile-heading"> Comment: </h4>
      <p class="profile-text"><%= @iteration_last.comment %></p>
      <div class="audio-panel">
        <audio controls>
          <source src="<%= @iteration_last.recording %>">
        </audio>
      </div>
  </div>
<% end %>

<%= link_to "All iterations", song_iterations_path(@song), class:"btn submit-button large-button" %>

<% if current_user && @band.user_in_band?(current_user.id) %>
<div class="iteration-form">
<%= form_for [@song, @iteration], :html => { :class => 'base-forms', multipart: true } do |f| %>
    <%= f.label :lyrics, class:"cool-label" %>
  <div class="form-group">
    <%= f.text_area :content, cols: "40", rows: "20", class:"input-medium form-width, lyric-field" %>
  </div>
    <%= f.label :recording, class:"cool-label" %>
  <div class="form-group">
    <%= f.text_field :recording, class:"form-width" %>
  </div>
    <%= f.label :comment, class:"cool-label" %>
  <div class="form-group">
    <%= f.text_area :comment, class: "form-width" %>
  </div>
  <div class="form-group">
    <%= f.submit "Create iteration", class:"submit-button btn large-button" %>
  </div>
</div>
<% end %>
<% end %>