config/routes.rb
Rails.application.routes.draw do
    root 'home#index'

    resources :musicians do
      resources :bands do
        post '/join_band', to: 'band_musicians#create'
        delete '/leave_band', to: 'band_musicians#destroy'
      end
    end

    resources :songs do
      resources :iterations
    end

    resources :bands, only: [:index]

    namespace :admin do
      resources :dashboard, only: [:index]
    end

    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
end

app/models/band.rb
class Band < ApplicationRecord

  validates_presence_of :genre,
                        :photo,
                        :name

  validates :name, uniqueness: true, presence: true

  has_many :band_musicians, dependent: :destroy
  has_many :songs, dependent: :destroy
  has_many :musicians, through: :band_musicians

  def user_in_band?(id)
    musicians.where(id: id).exists?
  end

  def owner
    musicians.first
  end

  def self.number_of_musicians
    joins(:musicians).group("name").count
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_musician, only: [:new, :create, :show, :edit, :update, :destroy]
  before_action :set_band, only: [:show, :edit, :update, :destroy]

  def new
    @musician = Musician.find(params[:musician_id])
    @band = Band.new
  end

  def create
    @musician = Musician.find(params[:musician_id])
    @band = @musician.bands.create(band_params)
    if @band.id
      redirect_to musician_band_path(@musician, @band)
    else
      flash.now[:alert] = @band.errors.full_messages.join("<br>").html_safe
      render :new
    end
  end

  def edit
  end

  def update
    @band.update(band_params)
    if @band.save
      flash[:success] = "Profile updated!"
      redirect_to musician_band_path(@musician, @band)
    else
      flash.now[:alert] = @band.errors.full_messages.join("<br>").html_safe
      render :edit
    end
  end

  def destroy
    if current_user && @band.owner
      name = @band.name
      @band.destroy

      flash[:success] = "You broke up #{name}"

      redirect_to musician_path(current_user)
    end
  end

  def show
  end


  def index
    @bands = Band.all
  end

  private

  def set_musician
    @musician = Musician.find_by(id: params[:musician_id])
  end

  def set_band
    @band = Band.find(params[:id])
  end

  def band_params
    params.require(:band).permit(:name, :photo, :genre)
  end
end

app/views/bands/edit.html.erb
<div class="col-sm-12 .col-centered text-center">
  <div class="profile-container">
  <%= form_for [@musician, @band], :html => { :class => 'base-forms' } do |f| %>
      <%= f.label :name %>
    <div class="form-group">
      <%= f.text_field :name, class:"input-medium" %>
    </div>
      <%= f.label :logo %>
    <div class="form-group">
      <%= f.text_field :photo %>
    </div>
      <%= f.label :genre %>
    <div>
      <%= f.text_field :genre %>
    </div>
    <div class="form-group">
      <%= f.submit "Update the band", class:"submit-button btn" %>
    </div>
  </div>
</div>
<% end %>

app/views/bands/index.html.erb
  <h1> Bands </h1>
  <% @bands.each do |band| %>
  <% if band.musicians.first %>
  <%= link_to musician_band_path(band.musicians.first, band) do %>
  <div class="mp-container">
    <div class="picture-container">
      <div class="imgdiv">
      </div>
    </div>
      <div class="profile-container">
        <p class="profile-text"><strong>Name:</strong> <%= band.name %></p>
        <p class="profile-text"><strong>Genre:</strong><%= band.genre %></p>
        <p class="profile-text"><strong>Members:</strong>
        <% band.musicians.each do |musician| %>
          <%= musician.name + "  " %>
        <% end %>
          <% if current_user && band.user_in_band?(current_user.id) == false %>
            <%= link_to "Join the band", musician_band_join_band_path(current_user, band), method:"post", class: "btn submit-button large-button", data: {confirm: "Are you sure?"} %>
          <% end %>
      </div>
  </div>
  <% end %>
  <% end %>
  <% end %>

app/views/bands/new.html.erb
<div class="all-forms">
  <%= form_for [@musician, @band], :html => { :class => 'base-forms' } do |f| %>
      <%= f.label :name, class: "cool-label" %>
    <div class="form-group">
      <%= f.text_field :name, class: "form-width" %>
    </div>
      <%= f.label :logo, class: "cool-label" %>
    <div class="form-group">
      <%= f.text_field :photo, class: "form-width" %>
    </div>
      <%= f.label :genre, class: "cool-label" %>
    <div>
      <%= f.text_field :genre, class: "form-width" %>
    </div>
    <div class="form-group">
      <%= f.submit "Make the band", class:"submit-button btn large-button" %>
    </div>
  </div>
<% end %>

app/views/bands/show.html.erb
<h1 class="show-headings">Band profile</h1>
<% if current_user && @band.user_in_band?(current_user.id) %>
  <div class="musician-profile-manager">
  <h5 class="musician-profile-heading"> You're in the band! </h5>
<% if current_user && @band.user_in_band?(current_user.id) && current_user.id == @band.owner.id %>
  <%= link_to edit_musician_band_path(current_user, @band) do %>
    <i class="far fa-edit"><span class="hidden">edit</span></i></i>
  <% end %>
  <%= link_to musician_band_path(current_user, @band), method:"delete", data: {confirm: "Are you sure?"} do %>
    <i class="fas fa-trash-alt"><span class="hidden">delete</span></i></i>
  <% end %>
<% end %>
</div>
<% end %>

<div class="mp-show-container">
  <div class="musician-container-show">
      <div class="imgdiv">
      </div>
        <h4 class="profile-heading">Name:</h4>
        <p class="profile-text"><%= @band.name %></p>
        <h4 class="profile-heading">Genre:</h4>
        <p class="profile-text"><%= @band.genre %></p>
        <h4 class="profile-heading">Members:</h4>

          <% @band.musicians.each do |musician| %>            
              <div class="member-profile">
              <p class="profile-text"><%= link_to musician.name, musician_path(musician) %> | <%= musician.instrument %></p>
              </div>
          <% end %>

        </div>
        <div class="musician-container-band-show">
        <h4 class="band-profile-heading">Songs</h4>
          <% @band.songs.each do |song| %>
            <p class="profile-text"><%= link_to song.title, song_path(song) %></p>
          <% end %>
        </div>
      </div>
    <% if current_user && @band.user_in_band?(current_user.id) == false %>
      <%= link_to "Join the band", musician_band_join_band_path(current_user, @band), method:"post", data: {confirm: "Are you sure?"}, class:"btn submit-button large-button" %>
    <% end %>
    <% if current_user && @band.user_in_band?(current_user.id) %>
      <div id="write-song">
        <%= link_to "Write a song", new_song_path(current_user, @band), class:"btn submit-button large-button" %>
      </div>
    <% end %>

      <% if current_user && @band.user_in_band?(current_user.id) %>
        <%= link_to "Break up the band", musician_band_leave_band_path(current_user, @band), method:"delete", data: {confirm: "Are you sure?"}, class:"btn submit-button large-button" %>
      <% end %>
    </div>
  </div>
</div>